### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jimsorock** [pubnub/typescript-ref-app-team-chat#2]
fresh clone of project, npm install then npm start. Filled in creds and app starts up with this error.

```
getNumericHash
src/foundations/utilities/getUniqueColor.tsx:4
  1 | const getUniqueColor = (string: string, colorSet: string[]) => {
  2 |   const getNumericHash = (string: string) => {
  3 |     let hash = 0;
> 4 |     if (string.length === 0) return hash;
  5 |     for (let i = 0; i < string.length; i++) {
  6 |       let char = string.charCodeAt(i);
  7 |       hash = (hash << 5) - hash + char;
```

**Comment by elviswolcott** [comment]
Thanks for reporting this @jimsorock 

There's an issue in the populate script that causes some users to not be created properly from the sample data. 
A fix is on the way, but in the meantime you can rerun the populate script to fill in the missing data.

```bash
node setup/populate.js
```

Then refresh the app and confirm that 100 users are in the introductions conversation.
If it is less than 100, you might have to rerun the populate script a few times to fill in all the gaps.

![Screenshot from 2020-05-19 13-34-14](https://user-images.githubusercontent.com/10013769/82359360-caef8500-99d5-11ea-83e1-55e304df8e2c.png)

Let me know if this works for you.

**Comment by nishith-pubnub** [comment]
@jimsorock If you can also confirm that the "Objects" feature is enabled on your account. The app uses this feature to populate sample data (users, conversations etc.).

**Comment by elviswolcott** [comment]
It doesn't look like this is any issue anymore, so I'm going to close this.

**Comment by sanya29** [comment]
I have this issue too. Also a fresh clone followed by `npm install` and `npm start`. Exact same error too. Refreshing multiple times usually fixes it, but it's a little unpredictable. Also any changes to `team-chat-initialization-data.json` aren't reflected for some reason?

**Comment by elviswolcott** [comment]
Unfortunately the current populate script isn't able to clear existing data after it has been populated, so the only way to use a different dataset is with a new key.

I'm working on some updates to the populate script to allow resetting/modifying existing data and fixing the consistency issues.

**Comment by elviswolcott** [comment]
@sanya29 v0.10.0 includes a new populate script that that is more reliable (and reports errors more clearly). We are now using Objects v2 (which means any existing objects data on your keys will *not* be used). 

The new populate script should allow you to add/modify the initialization data without trouble. It's worth noting that it will not remove metadata (i.e. if you remove `user1` from the initialization data, it will still exist on your keys).
